---
#RandomOre
Id: "14"
Meta: "0"
#Drops
1Drops: "263"
1Message: "§0Coal"
2Drops: "265"
2Message: "Iron"
3Drops: "266"
3Message: "§eGold"
4Drops: "331"
4Message: "§4Redstone"
5Drops: "264"
5Message: "§1Diamond"
...